"""add more tables

Revision ID: d075131d9032
Revises: d94a4b670f38
Create Date: 2023-04-02 20:37:52.379876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd075131d9032'
down_revision = 'd94a4b670f38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('petowner_id', sa.BigInteger(), nullable=False),
    sa.Column('pet_id', sa.BigInteger(), nullable=True),
    sa.Column('service_id', sa.BigInteger(), nullable=True),
    sa.Column('serviceprovider_id', sa.BigInteger(), nullable=True),
    sa.Column('duration', sa.Numeric(), server_default='1.0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('paid_amount', sa.Numeric(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('stripe_token', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['petowner_id'], ['petowners.user_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['serviceprovider_id'], ['serviceproviders.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('petowner_id', sa.BigInteger(), nullable=False),
    sa.Column('serviceprovider_id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=True),
    sa.Column('rating', sa.Numeric(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['petowner_id'], ['petowners.user_id'], ),
    sa.ForeignKeyConstraint(['serviceprovider_id'], ['serviceproviders.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('petowners', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('petowners', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('pets', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('pets', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('serviceproviders', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('serviceproviders', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('services', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('services', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'updated_at')
    op.drop_column('services', 'created_at')
    op.drop_column('serviceproviders', 'updated_at')
    op.drop_column('serviceproviders', 'created_at')
    op.drop_column('pets', 'updated_at')
    op.drop_column('pets', 'created_at')
    op.drop_column('petowners', 'updated_at')
    op.drop_column('petowners', 'created_at')
    op.drop_table('reviews')
    op.drop_table('bookings')
    # ### end Alembic commands ###
