"""update users petowners pet serviceproviders and services table

Revision ID: d94a4b670f38
Revises: 05484ff1e29a
Create Date: 2023-03-29 00:36:10.085328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94a4b670f38'
down_revision = '05484ff1e29a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
